import classNames from 'classnames'
import './globals.css'
import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'
import { UserProvider } from '@auth0/nextjs-auth0/client'

const manrope = Manrope({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={classNames(manrope.className, 'overflow-hidden')}>
        <UserProvider>{children}</UserProvider>
      </body>
    </html>
  )
}
